site_name: Notatki z Matematyki
use_directory_urls: false
theme:
  name: material
  features:
    - navigation.expand
  palette:
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/white-balance-sunny
        name: Switch to dark mode

nav:
  - Home: index.md
  - Algebra:
      - Macierze: macierze.md
      - Wyznaczniki: Wyznaczniki.md
      - Macierze-odwrotne: macierze-odwrotne.md
      - Równania w języku macierzy: równania-w-jezyku-macierzy.md
  - Geometria:
      - Wektory: wektory.md
      - Iloczyny: Iloczyny.md
      - Geometria-analityczna: geometria_analityczna.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list

extra_css:
  - https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;600;700&display=swap
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css
  - css/custom.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - js/katex-render.js
