site_name: Notatki z Matematyki
use_directory_urls: false
theme:
  name: material
  features:
    - navigation.expand
  palette:
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/white-balance-sunny
        name: Switch to dark mode

nav:
  - Home: index.md
  - Algebra:
      - Macierze: macierze.md
      - Wyznaczniki: Wyznaczniki.md
      - Macierze-odwrotne: macierze-odwrotne.md
      - Równania w języku macierzy: równania-w-jezyku-macierzy.md
      - Kalkulator macierzy: calc-test.html
  - Geometria:
      - Wektory: wektory.md
      - Iloczyny: Iloczyny.md
      - Geometria-analityczna: geometria_analityczna.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css


extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - js/katex.js
  - js/matrix-calculator.js